version: "3.8"

services:
  airflow:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username ${USERNAME} --password ${PASSWORD} --firstname ${FNAME} --lastname ${LNAME} --role Admin --email ${EMAIL} &&
               airflow scheduler & airflow webserver"